### ISSUE TITLE
things to consider fixing

### ISSUE THREAD

**Issue by amjed-98** [abedshamia/boilerplate_builder#2]
that's a great project you made  abed, you really solved a problem here
 I used it this morning and faced a couple of minor issues you could consider fixing in the future for a better user experience, or perhaps a developing experience:

- [x] maybe you could put the node_module folder in the .gitignore file, or you could place a warning in the readme or in the terminal that you're not ignoring node_modules.

![image](https://user-images.githubusercontent.com/78312641/159427138-bba6ef09-5210-4fbf-a8ad-bea2f408f9fb.png)

- [x] I think you forgot to destructure TEST_DATABASE_URL  in src/database/config/connection.js - line 3, because you're using it at line 17 

![image](https://user-images.githubusercontent.com/78312641/159427429-a0a5a7e2-c2ac-4ff7-a0fa-8bc8c9b31f14.png)
![image](https://user-images.githubusercontent.com/78312641/159427446-917ce5c0-3b61-4354-82f0-a0aae36e8dd4.png)

- [x] this isn't an issue actually, I just want to praise you for making a default case when NODE_ENV is undefined because this happens to me all the time when trying to set the DB URL but forget to add the NODE_ENV=dev or prod or test in the package.json and takes me a lot of time to debug, so yeah thanks for the hint and great work on everything else

![image](https://user-images.githubusercontent.com/78312641/159428431-5766e14b-fa5b-434d-9f20-d6413a9ecd81.png)

**Comment by abedshamia** [comment]
Thank you for taking time and writing this issue Amjed! I appreciate that

I've already fixed those issues, and even added more features,  just make sure to pull the latest version of the repo 😉

**Comment by amjed-98** [comment]
I guess i forked it the first time you deployed it and then never updated my forked repo.
My bad 😅
